# This is a basic workflow to help you get started with Actions

name: Build

on:
  
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone a repo 
        run: |
         git clone https://github.com/farrukh90/artemis.git


      - name: Change version
        working-directory: artemis
        run: |
         git checkout 2.0.0


      - name: Build Image
        working-directory: artemmis
        run: |
         docker image build -t  us-central1-docker.pkg.dev/terraform-project-aug/artemis/artemis:2.0.0   . 


      # Authenticate to GCP
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'
    
      - name: Authenticate to repository
        run: |
          gcloud auth configure-docker  us-central1-docker.pkg.dev

        


      - name: Push  Image
        working-directory: artemmis
        run: |
         docker image push  us-central1-docker.pkg.dev/terraform-project-aug/artemis/artemis:2.0.0 



