# This is a basic workflow to help you get started with Actions

name: Build

on:
  
  push:
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone a repo 
        run: |
         git clone https://github.com/farrukh90/artemis.git


      - name: Change version
        run: |
         git checkout 2.0.0
